import * as Components from '../index'

test('Exposed API', () => {
  // Base UI Components
  expect(Components.Alert).toBeDefined()
  expect(Components.AnnotatedString).toBeDefined()
  expect(Components.AssistiveText).toBeDefined()
  expect(Components.Boolean).toBeDefined()
  expect(Components.BooleanArray).toBeDefined()
  expect(Components.Button).toBeDefined()
  expect(Components.ColumnLayout).toBeDefined()
  expect(Components.Container).toBeDefined()
  expect(Components.Control).toBeDefined()
  expect(Components.Date).toBeDefined()
  expect(Components.Document).toBeDefined()
  expect(Components.DocumentArray).toBeDefined()
  expect(Components.Flex).toBeDefined()
  expect(Components.Heading).toBeDefined()
  expect(Components.Icon).toBeDefined()
  expect(Components.Label).toBeDefined()
  expect(Components.Link).toBeDefined()
  expect(Components.List).toBeDefined()
  expect(Components.Menu).toBeDefined()
  expect(Components.Paging).toBeDefined()
  expect(Components.Pane).toBeDefined()
  expect(Components.Popover).toBeDefined()
  expect(Components.Portal).toBeDefined()
  expect(Components.Search).toBeDefined()
  expect(Components.Select).toBeDefined()
  expect(Components.SideNav).toBeDefined()
  expect(Components.Stack).toBeDefined()
  expect(Components.String).toBeDefined()
  expect(Components.Table).toBeDefined()
  expect(Components.Text).toBeDefined()
  expect(Components.TextArea).toBeDefined()
  expect(Components.Toaster).toBeDefined()

  // Wrapped Fields
  expect(Components.AnnotatedStringField).toBeDefined()
  expect(Components.BooleanField).toBeDefined()
  expect(Components.BooleanArrayField).toBeDefined()
  expect(Components.DateField).toBeDefined()
  expect(Components.DocumentField).toBeDefined()
  expect(Components.DocumentArrayField).toBeDefined()
  expect(Components.LinkField).toBeDefined()
  expect(Components.SelectField).toBeDefined()
  expect(Components.TableField).toBeDefined()
  expect(Components.StringField).toBeDefined()
  expect(Components.TextAreaField).toBeDefined()
})
